Every year many students give the GRE exam to get admission in foreign Universities. The data set contains GRE Scores (out of 340), TOEFL Scores (out of 120), University Rating (out of 5), Statement of Purpose strength (out of 5), Letter of Recommendation strength (out of 5), Undergraduate GPA (out of 10), Research Experience (0=no, 1=yes), Admitted (0=no, 1=yes). Admitted is the target variable.
Data Set Available on kaggle (The last column of the dataset needs to be changed to 0 or 1)Data Set : https://www.kaggle.com/mohansacharya/graduate-admissions
The counselor of the firm is supposed check whether the student will get an admission or not based on his/her GRE score and Academic Score. So to help the counselor to take appropriate decisions build a machine learning model classifier using Decision tree to predict whether a student will get admission or not.
Apply Data pre-processing (Label Encoding, Data Transformationâ€¦.) techniques if necessary.
Perform data-preparation (Train-Test Split)
C. Apply Machine Learning Algorithm
D. Evaluate Model.

In [5]:
import pandas as pd

In [6]:
raw_data = pd.read_csv("Admission_Predict.csv")
raw_data.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [7]:
target = raw_data["Chance_Of_Admit"]
data = raw_data.drop(columns=["Serial_No","Chance_Of_Admit"])

KeyError: 'Chance_Of_Admit'

In [ ]:
from sklearn import tree
from sklearn.model_selection import train_test_split

In [ ]:
train,test,target_train,target_test = train_test_split(data,target,test_size=0.20)

In [ ]:
model = tree.DecisionTreeRegressor()
model.fit(train,target_train)

DecisionTreeRegressor()

In [ ]:
print("Accuracy: ",model.score(test,target_test))

Accuracy:  0.6754829489099072

In [ ]:
prediction = model.predict(test)
new_data = test
new_data["Predicted_data"] = prediction
new_data["Actual_data"] = target_test
new_data.sort_index()

<ipython-input-63-4c8a23611df0>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data["Predicted_data"] = prediction
<ipython-input-63-4c8a23611df0>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data["Actual_data"] = target_test

,GRE_Score,TOEFL_Score,University Rating,SOP,LOR,CGPA,Research,Predicted_data,Actual_data
26,322,109,5,4.5,3.5,8.80,0,0.76,0.76
27,298,98,2,1.5,2.5,7.50,1,0.64,0.44
28,295,93,1,2.0,2.0,7.20,0,0.47,0.46
31,327,103,3,4.0,4.0,8.30,1,0.52,0.74
35,320,110,5,5.0,5.0,9.20,1,0.86,0.88
...,...,...,...,...,...,...,...,...,...
382,324,110,4,4.5,4.0,9.15,1,0.82,0.82
388,296,97,2,1.5,2.0,7.80,0,0.54,0.49
391,318,106,3,2.0,3.0,8.65,0,0.66,0.71
396,325,107,3,3.0,3.5,9.11,1,0.83,0.84
399,333,117,4,5.0,4.0,9.66,1,0.94,0.95